import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type JsonSchema = {
  type?: string | string[];
  const?: string;
  enum?: string[];
  required?: string[];
  properties?: Record<string, JsonSchema>;
  additionalProperties?: boolean | JsonSchema;
  items?: JsonSchema;
  $ref?: string;
};

const contractPath = resolve(import.meta.dir, "../../../contracts/openapi.json");
const outputPath = resolve(import.meta.dir, "../src/generated.ts");
const contract = JSON.parse(readFileSync(contractPath, "utf8")) as {
  components: {
    schemas: Record<string, JsonSchema>;
  };
};

const schemas = contract.components.schemas;
const output = `${[
  "// Generated by packages/api-client/scripts/generate-types.ts. Do not edit by hand.",
  ...Object.entries(schemas).map(([name, schema]) => renderSchema(name, schema)),
  'export type HealthResponse = "ok";',
].join("\n\n")}\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);

function renderSchema(name: string, schema: JsonSchema): string {
  // A named schema that is not an object is a reusable scalar, typically an
  // enum shared by several DTOs. It becomes a type alias so both sides of the
  // contract keep one spelling of the value set.
  if (schema.type !== "object" || !schema.properties) {
    const rendered = renderType(schema);
    const single = `export type ${name} = ${rendered};`;

    // Long unions are wrapped so the emitted file matches the repository
    // formatter and does not fail a lint run.
    if (single.length <= 88 || !schema.enum) {
      return single;
    }

    const members = schema.enum
      .map((value) => `  | ${JSON.stringify(value)}`)
      .join("\n");
    return `export type ${name} =\n${members};`;
  }

  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties)
    .map(([property, propertySchema]) => {
      const optional = required.has(property) ? "" : "?";
      return `  ${property}${optional}: ${renderType(propertySchema)};`;
    })
    .join("\n");

  return `export interface ${name} {\n${fields}\n}`;
}

function renderType(schema: JsonSchema): string {
  if (schema.$ref) {
    return schema.$ref.split("/").at(-1) ?? "unknown";
  }

  // OpenAPI 3.1 spells a nullable field as a type union rather than the 3.0
  // `nullable: true`. Rendering the union member by member keeps `null` in the
  // emitted type instead of silently dropping it, which would let the frontend
  // assume a value is always present.
  if (Array.isArray(schema.type)) {
    return schema.type
      .map((type) => renderType({ ...schema, type }))
      .join(" | ");
  }

  if (schema.type === "null") {
    return "null";
  }

  if (schema.const) {
    return JSON.stringify(schema.const);
  }

  if (schema.enum) {
    return schema.enum.map((item) => JSON.stringify(item)).join(" | ");
  }

  if (schema.type === "string") {
    return "string";
  }

  if (schema.type === "boolean") {
    return "boolean";
  }

  // JSON has one numeric type, so both spellings map to `number`.
  if (schema.type === "integer" || schema.type === "number") {
    return "number";
  }

  if (schema.type === "array") {
    if (!schema.items) {
      throw new Error("Array schema requires items");
    }
    return `${renderType(schema.items)}[]`;
  }

  if (schema.type === "object") {
    return "Record<string, unknown>";
  }

  throw new Error(`Unsupported schema type: ${JSON.stringify(schema)}`);
}
