import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type JsonSchema = {
  type?: string;
  const?: string;
  enum?: string[];
  required?: string[];
  properties?: Record<string, JsonSchema>;
  $ref?: string;
};

const contractPath = resolve(import.meta.dir, "../../../contracts/openapi.json");
const outputPath = resolve(import.meta.dir, "../src/generated.ts");
const contract = JSON.parse(readFileSync(contractPath, "utf8")) as {
  components: {
    schemas: Record<string, JsonSchema>;
  };
};

const schemas = contract.components.schemas;
const output = [
  "// Generated by packages/api-client/scripts/generate-types.ts. Do not edit by hand.",
  ...Object.entries(schemas).map(([name, schema]) => renderSchema(name, schema)),
  'export type HealthResponse = "ok";'
].join("\n\n") + "\n";

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);

function renderSchema(name: string, schema: JsonSchema): string {
  if (schema.type !== "object" || !schema.properties) {
    throw new Error(`Unsupported schema for ${name}`);
  }

  const required = new Set(schema.required ?? []);
  const fields = Object.entries(schema.properties)
    .map(([property, propertySchema]) => {
      const optional = required.has(property) ? "" : "?";
      return `  ${property}${optional}: ${renderType(propertySchema)};`;
    })
    .join("\n");

  return `export interface ${name} {\n${fields}\n}`;
}

function renderType(schema: JsonSchema): string {
  if (schema.$ref) {
    return schema.$ref.split("/").at(-1) ?? "unknown";
  }

  if (schema.const) {
    return JSON.stringify(schema.const);
  }

  if (schema.enum) {
    return schema.enum.map((item) => JSON.stringify(item)).join(" | ");
  }

  if (schema.type === "string") {
    return "string";
  }

  if (schema.type === "boolean") {
    return "boolean";
  }

  throw new Error(`Unsupported schema type: ${JSON.stringify(schema)}`);
}
