// Generated by packages/api-client/scripts/generate-types.ts. Do not edit by hand.

export interface ApiErrorResponse {
  code: string;
  details?: Record<string, unknown>;
  message: string;
  requestId: string;
}

export interface CapabilityFlags {
  aiArchiveEnabled: boolean;
  attachmentsEnabled: boolean;
  authMockEnabled: boolean;
  desktopEnabled: boolean;
}

export interface CurrentUser {
  displayName: string;
  id: string;
  organizations: OrganizationMembership[];
  systemRole: "student" | "organization_member" | "moderator" | "admin";
}

export interface LoginResponse {
  expiresAt: string;
  token: string;
  user: CurrentUser;
}

export interface MetaResponse {
  appName: "Campus Agora";
  capabilities: CapabilityFlags;
  version: string;
}

export interface MockLoginRequest {
  persona: "student" | "organization_member" | "moderator" | "admin";
}

export interface OrganizationMembership {
  name: string;
  organizationId: string;
  slug: string;
}

export interface ReadinessChecks {
  postgres: "ok" | "unavailable";
}

export interface ReadinessResponse {
  checks: ReadinessChecks;
  status: "ready" | "unready";
}

export interface SessionResponse {
  expiresAt: string;
  user: CurrentUser;
}

export type HealthResponse = "ok";
