// Generated by packages/api-client/scripts/generate-types.ts. Do not edit by hand.

export interface AcceptAnswerRequest {
  commentId?: string | null;
}

export interface AiDraft {
  entry: KnowledgeEntry;
  sources: ArchiveSource[];
}

export interface ApiErrorResponse {
  code: string;
  details?: Record<string, unknown>;
  message: string;
  requestId: string;
}

export type ApplicableAudience =
  | "all_students"
  | "new_students"
  | "undergraduate"
  | "graduate"
  | "organization_members";

export type ArchiveCategory =
  | "onboarding"
  | "campus_life"
  | "academics"
  | "organizations"
  | "procedures"
  | "other";

export interface ArchiveSource {
  createdAt: string;
  entryId: string;
  sourceAuthorId: string;
  sourceAuthorName: string;
  sourceCommentId?: string | null;
  sourcePostId: string;
  sourceTitle: string;
}

export interface ArchiveSourceCollection {
  items: ArchiveSource[];
}

export interface CapabilityFlags {
  aiArchiveEnabled: boolean;
  attachmentsEnabled: boolean;
  authMockEnabled: boolean;
  desktopEnabled: boolean;
}

export interface ChangeStatusRequest {
  status: ModerationStatus;
}

export interface ContentReport {
  category: ReportCategory;
  createdAt: string;
  id: string;
  message: string;
  postId: string;
  reporterId: string;
  resolution?: string | null;
  resolvedAt?: string | null;
  resolvedBy?: string | null;
}

export interface ContentReportCollection {
  items: ContentReport[];
}

export interface Correction {
  createdAt: string;
  id: string;
  message: string;
  postId: string;
  reporterId: string;
  resolvedAt?: string;
  resolvedBy?: string;
}

export interface CorrectionCollection {
  items: Correction[];
}

export interface CreateDiscussionRequest {
  body: string;
  tags?: string[];
  title: string;
}

export interface CreateKnowledgeEntryRequest {
  applicableAudience: ApplicableAudience;
  body: string;
  category: ArchiveCategory;
  sourceKind: SourceKind;
  sourceReference?: string;
  summary?: string;
  tags?: string[];
  title: string;
}

export interface CreateReportRequest {
  category: ReportCategory;
  message: string;
  postId: string;
}

export interface CurrentUser {
  displayName: string;
  id: string;
  organizations: OrganizationMembership[];
  systemRole: "student" | "organization_member" | "moderator" | "admin";
}

export interface DerivedEntry {
  createdAt: string;
  entryId: string;
  moderationStatus: ModerationStatus;
  title: string;
}

export interface DerivedEntryCollection {
  items: DerivedEntry[];
}

export interface Discussion {
  acceptedCommentId?: string | null;
  authorId: string;
  body: string;
  createdAt: string;
  id: string;
  moderationStatus: ModerationStatus;
  replyCount: number;
  tags: string[];
  title: string;
  updatedAt: string;
}

export interface DiscussionReply {
  authorId: string;
  body: string;
  createdAt: string;
  id: string;
  postId: string;
  updatedAt: string;
}

export interface DiscussionReplyCollection {
  items: DiscussionReply[];
}

export interface FileCorrectionRequest {
  message: string;
}

export interface KnowledgeEntry {
  aiProvider?: string | null;
  applicableAudience: ApplicableAudience;
  authorId: string;
  body: string;
  category: ArchiveCategory;
  createdAt: string;
  currentRevision: number;
  id: string;
  moderationStatus: ModerationStatus;
  sourceKind: SourceKind;
  sourceReference?: string;
  summary?: string;
  tags: string[];
  title: string;
  updatedAt: string;
}

export interface LoginResponse {
  expiresAt: string;
  token: string;
  user: CurrentUser;
}

export interface MetaResponse {
  appName: "Campus Agora";
  capabilities: CapabilityFlags;
  version: string;
}

export interface MockLoginRequest {
  persona: "student" | "organization_member" | "moderator" | "admin";
}

export interface ModerationQueueItem {
  authorId: string;
  moderationStatus: ModerationStatus;
  openReportCount: number;
  postId: string;
  postKind: "knowledge" | "discussion";
  queuedAt: string;
  risk: RiskLevel;
  title: string;
}

export type ModerationStatus =
  | "draft"
  | "published"
  | "hidden"
  | "rejected"
  | "archived"
  | "pending_review";

export interface OrganizationMembership {
  name: string;
  organizationId: string;
  slug: string;
}

export interface PaginatedDiscussions {
  items: Discussion[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

export interface PaginatedKnowledgeEntries {
  items: KnowledgeEntry[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

export interface PaginatedModerationQueue {
  items: ModerationQueueItem[];
  page: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
}

export interface PromoteRequest {
  applicableAudience?: string | null;
  body?: string | null;
  category?: string | null;
  commentId?: string | null;
  summary?: string | null;
  tags?: string[] | null;
  title?: string | null;
}

export interface Promotion {
  entry: KnowledgeEntry;
  source: ArchiveSource;
}

export interface ReadinessChecks {
  postgres: "ok" | "unavailable";
}

export interface ReadinessResponse {
  checks: ReadinessChecks;
  status: "ready" | "unready";
}

export interface ReplyRequest {
  body: string;
}

export type ReportCategory =
  | "spam"
  | "harassment"
  | "privacy_violation"
  | "misinformation"
  | "illegal"
  | "other";

export type ReportResolution = "upheld" | "dismissed";

export interface ResolveReportRequest {
  resolution: ReportResolution;
}

export interface Revision {
  body: string;
  createdAt: string;
  editorId: string;
  id: string;
  revision: number;
  summary?: string;
  tags: string[];
  title: string;
}

export interface RevisionCollection {
  items: Revision[];
}

export type RiskLevel = "none" | "low" | "medium" | "high";

export interface SessionResponse {
  expiresAt: string;
  user: CurrentUser;
}

export type SourceKind =
  | "firsthand_experience"
  | "official_announcement"
  | "group_chat"
  | "discussion"
  | "unspecified";

export interface UpdateKnowledgeEntryRequest {
  applicableAudience?: ApplicableAudience;
  body?: string;
  category?: ArchiveCategory;
  sourceKind?: SourceKind;
  sourceReference?: string;
  summary?: string;
  tags?: string[];
  title?: string;
}

export type HealthResponse = "ok";
